create table if not exists public.todos (
  id bigint generated by default as identity primary key,
  name text not null,
  created_at timestamp with time zone default now() not null
);

insert into public.todos (name)
values
  ('Take Maple on a sunset walk'),
  ('Refill the treat jar'),
  ('Upload a new Pet Whisper photo')
on conflict do nothing;
