import { cookies } from "next/headers";
import { createClient } from "@/utils/supabase/server";

type Todo = {
  id: string | number;
  name: string;
};

const createTodosTableSql = `create table if not exists public.todos (
  id bigint generated by default as identity primary key,
  name text not null,
  created_at timestamp with time zone default now() not null
);

insert into public.todos (name)
values
  ('Take Maple on a sunset walk'),
  ('Refill the treat jar'),
  ('Upload a new Pet Whisper photo')
on conflict do nothing;`;

export default async function SupabaseDemoPage() {
  const cookieStore = await cookies();
  const supabase = createClient(cookieStore);
  const { data: todos, error } = await supabase.from("todos").select();

  return (
    <main className="mx-auto max-w-3xl px-6 py-12">
      <h1 className="text-3xl font-semibold text-stone-950">Supabase Demo</h1>
      <p className="mt-3 text-sm text-stone-500">
        Reading the <code>todos</code> table with the server client.
      </p>
      {error ? (
        <div className="mt-8 rounded-2xl border border-amber-200 bg-amber-50 px-4 py-4 text-sm text-amber-900">
          <p className="font-medium">Supabase is connected, but the demo query failed.</p>
          <p className="mt-2">
            {error.message}
          </p>
          <p className="mt-2 text-amber-800/80">
            Create a <code>public.todos</code> table or update this page to query an
            existing table in your project.
          </p>
          <pre className="mt-4 overflow-x-auto rounded-2xl bg-stone-950 px-4 py-4 text-xs leading-6 text-stone-100">
            <code>{createTodosTableSql}</code>
          </pre>
        </div>
      ) : todos?.length ? (
        <ul className="mt-8 space-y-3">
          {(todos as Todo[] | null)?.map((todo) => (
            <li
              key={todo.id}
              className="rounded-2xl border border-stone-200 bg-white px-4 py-3 text-stone-800"
            >
              {todo.name}
            </li>
          ))}
        </ul>
      ) : (
        <div className="mt-8 rounded-2xl border border-stone-200 bg-white px-4 py-4 text-sm text-stone-700">
          <p className="font-medium">The <code>todos</code> table is connected, but it is empty.</p>
          <p className="mt-2 text-stone-500">
            You can add a few rows in Supabase and refresh this page to verify the
            server client is working end to end.
          </p>
        </div>
      )}
    </main>
  );
}
